---
swagger: "2.0"
info:
  description: "AROF Configuration API"
  version: "0.0.1"
  title: "AROF API"
host: "localhost:5001"
basePath: "/api"
schemes:
- "http"
paths:
  /arof:
    get:
      summary: "Retrieve configuration"
      description: "Retrieve operation of resource: laser"
      operationId: "retrieve_configuration"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/arof-parameters"
        "400":
          description: "Internal Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      summary: "Create configuration"
      description: "Create arof configuration"
      operationId: "create_configuration"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "arof_pool"
        description: "arof pool"
        required: true
        schema:
          $ref: "#/definitions/arof-parameters"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/arof-parameters"
        "400":
          description: "Invalid ID supplied"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    put:
      summary: "Update configuration"
      description: "Update arof configuration"
      operationId: "update_configuration"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "arof_pool"
        description: "arof pool"
        required: true
        schema:
          $ref: "#/definitions/arof-parameters"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/arof-parameters"
        "400":
          description: "Invalid ID supplied"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      summary: "Delete configuration"
      description: "Delete all configuration"
      operationId: "delete_configuration"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Internal Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  arof-parameters:
    type: "object"
    properties:
      arof-pool:
        type: "array"
        items:
          $ref: "#/definitions/arof"
    example:
      arof-pool:
      - arof-id: 0
        enabled: true
        wavelength: 1550
      - arof-id: 1
        enabled: false
        wavelength: 1550
  arof:
    type: "object"
    properties:
      arof-id:
        type: "integer"
      enabled:
        type: "boolean"
      wavelength:
        type: "integer"
    example:
      arof-id: 0
      enabled: true
      wavelength: 1550
