---
swagger: "2.0"
info:
  description: "AROF Configuration API"
  version: "1.0.0"
  title: "AROF API"
host: "10.1.7.65:5001"
basePath: "/api"
schemes:
- "http"
paths:
  /arof/{arof_id}:
    post:
      summary: "Create configuration by ID"
      description: "Create operation of resource: laser"
      operationId: "create_configuration_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "arof_id"
        in: "path"
        description: "arof id"
        required: true
        type: "integer"
      - name: "enable"
        in: "query"
        description: "enable or disable the laser"
        required: false
        type: "boolean"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Operation"
        400:
          description: "Invalid ID supplied"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    put:
      summary: "Update configuration by ID"
      description: "Update operation of resource: laser"
      operationId: "update_arof_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "arof_id"
        in: "path"
        description: "arof id"
        required: true
        type: "integer"
      - name: "enable"
        in: "query"
        description: "enable or disable the laser"
        required: false
        type: "boolean"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Operation"
        400:
          description: "Invalid ID supplied"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      summary: "Delete configuration by ID"
      description: "Delete operation of resource: laser"
      operationId: "delete_configuration_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "arof_id"
        in: "path"
        description: "arof id"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Internal Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /arof:
    get:
      summary: "Retrieve configuration"
      description: "Retrieve operation of resource: laser"
      operationId: "retrieve_configuration"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Operation"
        400:
          description: "Internal Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Operation:
    type: "object"
    properties:
      arof_id:
        type: "integer"
      enable:
        type: "boolean"
    example:
      arof_id: 1
      enable: true
