---
swagger: "2.0"
info:
  description: "OBFN Configuration API"
  version: "0.1"
  title: "OBFN API"
host: "10.1.7.84:5002"
basePath: "/api"
schemes:
- "http"
paths:
  /obfn:
    get:
      summary: "Retrieve configuration"
      description: "Retrieve operations of resource: beams"
      operationId: "retrieve_configuration"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/obfn-parameters"
        "400":
          description: "Internal Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      summary: "Create configuration"
      description: "Create operations of resource: beams"
      operationId: "create_configuration"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "operations"
        required: true
        schema:
          $ref: "#/definitions/obfn-parameters"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/obfn-parameters"
        "400":
          description: "Invalid parameters supplied"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    put:
      summary: "Update configuration"
      description: "Update operation of resource: beams"
      operationId: "update_configuration"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "operations"
        required: true
        schema:
          $ref: "#/definitions/obfn-parameters"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/obfn-parameters"
        "400":
          description: "Invalid ID supplied"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      summary: "Delete configuration"
      description: "Delete operations of resource: beams"
      operationId: "delete_configuration"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Internal Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  obfn-parameters:
    type: "object"
    properties:
      obfn-pool:
        type: "array"
        items:
          $ref: "#/definitions/obfn"
      wavelength:
        type: "number"
    example:
      obfn-pool:
      - beam_id: 0
        beam_enable: true
        x_offset_angle: -90
        y_offset_angle: 90
        width: 502
      - beam_id: 1
        beam_enable: false
        x_offset_angle: 70
        y_offset_angle: 70
        width: 123
      wavelength: 1553
  obfn:
    type: "object"
    properties:
      beam_id:
        type: "integer"
      beam_enable:
        type: "boolean"
      x_offset_angle:
        type: "number"
      y_offset_angle:
        type: "number"
      width:
        type: "number"
    example:
      beam_id: 0
      beam_enable: true
      x_offset_angle: -90
      y_offset_angle: 90
      width: 502
