---
swagger: "2.0"
info:
  description: "OBFN Configuration API"
  version: "0.1"
  title: "OBFN API"
host: "10.1.7.84:5002"
basePath: "/api"
schemes:
- "http"
paths:
  /obfn:
    get:
      summary: "Retrieve configuration"
      description: "Retrieve OBFN configuration"
      operationId: "retrieve_configuration"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/obfn-parameters"
        "400":
          description: "Internal Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      summary: "Create configuration"
      description: "Create OBFN configuration"
      operationId: "create_configuration"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "obfn_params"
        description: "operations"
        required: true
        schema:
          $ref: "#/definitions/obfn-parameters"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/obfn-parameters"
        "400":
          description: "Invalid parameters supplied"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    put:
      summary: "Update configuration"
      description: "Update OBFN configuration"
      operationId: "update_configuration"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "obfn_params"
        description: "operations"
        required: true
        schema:
          $ref: "#/definitions/obfn-parameters"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/obfn-parameters"
        "400":
          description: "Invalid ID supplied"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      summary: "Delete configuration"
      description: "Delete OBFN configuration"
      operationId: "delete_configuration"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Internal Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  obfn-parameters:
    type: "object"
    properties:
      obfn-pool:
        type: "array"
        items:
          $ref: "#/definitions/obfn"
      wavelength-reference-pool:
        type: "array"
        items:
          $ref: "#/definitions/wavelength-reference"
    example:
      obfn-pool:
      - beam-id: 0
        beam-enable: true
        x-offset-angle: -90
        y-offset-angle: 90
        width: 502
      - beam-id: 1
        beam-enable: false
        x-offset-angle: 70
        y-offset-angle: 70
        width: 123
      wavelength: 1553
  obfn:
    type: "object"
    properties:
      beam-id:
        type: "integer"
      beam-enable:
        type: "boolean"
      x-offset-angle:
        type: "number"
      y-offset-angle:
        type: "number"
      width:
        type: "number"
  wavelength-reference:
    type: "object"
    properties:
      wavelength-id:
        type: "integer"
      central-frequency:
        $ref: '#/definitions/central-frequency'
  central-frequency:
    type: "object"
    properties:
      frequency-constraint:
        $ref: "#/definitions/frequency-constraint"
      central-frequency:
        type: "integer"
    example:
      beam-id: 0
      beam-enable: true
      x-offset-angle: -90
      y-offset-angle: 90
      width: 502
  frequency-constraint:
    type: "object"
    properties:
      adjustment-granularity:
        type: "string"
      grid-type:
        type: "string"
